#!/bin/sh

if [ $# -eq 0 ] ; then
echo "Compiling..."
skm clang++ program.cpp ./Source/GameData/Entities/*.cpp ./Source/GameData/*.cpp ./Source/MenuData/*.cpp ./Source/Utilities/*.cpp -o LostInSpace.exe
echo "🎉 Game Has Been Compiled!" 
fi

if [ $# -eq 1 ] ; then
    if [ "$1" = "setup" ] ; then
        echo "Loading..."
        skm new c++
        echo "Completed 1/2"
        skm clang++ program.cpp ./Source/GameData/Entities/*.cpp ./Source/GameData/*.cpp ./Source/MenuData/*.cpp ./Source/Utilities/*.cpp -o LostInSpace.exe 
        echo "Completed 2/2: 🎉 Game Has Been Compiled!" 
    else
        echo "Wut?..."
        
    fi
fi

# skm new c++ # Generate the C++ resources
# skm clang++ program.cpp ./Source/GameData/Entities/*.cpp ./Source/GameData/*.cpp ./Source/MenuData/*.cpp ./Source/Utilities/*.cpp -o LostInSpace.exe # Compile the program
# ./LostInSpace.exe # Run the application